version: '3'

volumes:
  shared_data:
      driver: local
  mysql_data:
      driver: local
  mongodb_data_container:    

services:
  mysql:
      network_mode: "host"
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak_test:
    network_mode: "host"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./imports/cache_reload/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./imports/themes/custom/:/opt/jboss/keycloak/themes/custom-theme/
    depends_on: 
      - mysql
  dbmongo:
    image: mongo:latest
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes: 
      - mongodb_data_container:/data/db  
